### PR TITLE
Add user profile page and reset user information page

### PR DESCRIPTION
**Pull request by ho-yi-shiuan**
# Description

Add user profile page and reset user information page 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing 
- [ ] Change that requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manual Test
- [ ] Unit Test
- [ ] Integration / End-to-End Test

**Test Configuration**:
* Browser vendor and version: e.g., Chrome Version 91.0.4472.164 (Official Build) (64-bit)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas that are not self-documenting
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings 
- [x] My changes have no unnecessary logging
- [ ] I have added tests that prove my fix is effective or that my feature works, for sufficiently complex features
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Sensitive info like tokens, secrets, and passwords have been removed before submitting

Modified from this article:
Phillip Johnston, “A GitHub Pull Request Template for Your Projects - Embedded Artistry,” Embedded Artistry, Aug. 04, 2017. https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/ (accessed Jul. 22, 2021).

### CODE REVIEW

**Comment by parseccentric** [comment]
Things to manually test for edit account page:

* Change just first / last name / password -> Only that field should change
* Enter matching passwords -> Form succeeds
* Enter mismatching passwords -> Form shows error

Things to manually test for (view) account page:

* Visit page -> info should be correct (FirstName LastName, email, asset list (just owned by user, public & private together)
* Use asset search bar -> assets should filter by matching substring on the name
* Press edit button -> should navigate to edit account page

**Comment by ho-yi-shiuan** [comment]
Test for cross-site scripting:
  tested1. <scr<script>ipt>alert(document.cookie)</script>
            2. " onfocus="alert(document.cookie)
            3. "><script >alert(document.cookie)</script >
Add error for when text input is blank:
  User can't click reset button now if 
            1. no input 
            2. input is blank 
            3. email field is not a valid email
Cancel button added

**Comment by ho-yi-shiuan** [comment]
**Test for cross-site scripting**:
* <scr<script>ipt>alert(document.cookie)</script>
* " onfocus="alert(document.cookie)
* "><script >alert(document.cookie)</script >

**Add error for when text input is blank**:
  User can't click reset button now if 
* no input 
* input is blank 
* email field is not a valid email

**Cancel button added**
**Combined routes to profile page and reset user page**
**Deleted unused asset array in profile page**

**Comment by parseccentric** [comment]
Great work! I put this through rigorous testing and nearly everything passed, which is super. I saw a couple of usability inconveniences that you may consider fixing as part of this pull request: 

* Email should auto-populate when navigating to edit user info page
* Reset button should say "Submit", not "Reset"
* Password field should work like this: 
    * both fields blank -> enable reset button (and do not change password)
    * one field blank -> disable reset button
    * both fields filled in -> enable reset button
    
Please message me with which changes you might be able to achieve before tomorrow's code deadline. You dont *have* to complete all of these by the deadline, but do let me know which ones will make it in. I'll do a merge tomorrow.

**Review by parseccentric — APPROVED** [review]

**Pull request merged**
